services:
  nestjs-api:
    build: 
      context: .
      dockerfile: Dockerfile
    # volumes:
      # NOTE: Uncomment for local dev?
      # - .:/app
      # - /app/node_modules
    # working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    