FROM node:20.5.0

WORKDIR /app

COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN \
	if [ -f package-lock.json ]; then npm ci; \
	elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install; \
	elif [ -f yarn.lock ]; then yarn install; \
	else npm install; fi

COPY . .

EXPOSE 8080

CMD ["npm", "run", "start:dev"]
